//
// Created by timur on 16.03.2020.
//

#ifndef COMPILERS_02_PARSERS_DECLARATIONS_CLASSDECLARATION_H_
#define COMPILERS_02_PARSERS_DECLARATIONS_CLASSDECLARATION_H_

class ClassDeclaration {};

#endif // COMPILERS_02_PARSERS_DECLARATIONS_CLASSDECLARATION_H_
