//
// Created by timur on 16.03.2020.
//

#ifndef COMPILERS_02_PARSERS_DECLARATIONS_CLASSDECLARATIONLIST_H_
#define COMPILERS_02_PARSERS_DECLARATIONS_CLASSDECLARATIONLIST_H_

class ClassDeclarationList {};

#endif // COMPILERS_02_PARSERS_DECLARATIONS_CLASSDECLARATIONLIST_H_
