//
// Created by timur on 16.03.2020.
//

#ifndef COMPILERS_02_PARSERS_DECLARATIONS_DECLARATION_H_
#define COMPILERS_02_PARSERS_DECLARATIONS_DECLARATION_H_

class Declaration {};

#endif // COMPILERS_02_PARSERS_DECLARATIONS_DECLARATION_H_
