//
// Created by timur on 16.03.2020.
//

#ifndef COMPILERS_02_PARSERS_DECLARATIONS_DECLARATIONLIST_H_
#define COMPILERS_02_PARSERS_DECLARATIONS_DECLARATIONLIST_H_

class DeclarationList {};

#endif // COMPILERS_02_PARSERS_DECLARATIONS_DECLARATIONLIST_H_
