//
// Created by timur on 16.03.2020.
//

#ifndef COMPILERS_02_PARSERS_DECLARATIONS_LOCALVARIABLEDECLARATION_H_
#define COMPILERS_02_PARSERS_DECLARATIONS_LOCALVARIABLEDECLARATION_H_

class LocalVariableDeclaration {};

#endif // COMPILERS_02_PARSERS_DECLARATIONS_LOCALVARIABLEDECLARATION_H_
