//
// Created by timur on 16.03.2020.
//

#ifndef COMPILERS_02_PARSERS_DECLARATIONS_METHODDECLARATION_H_
#define COMPILERS_02_PARSERS_DECLARATIONS_METHODDECLARATION_H_

class MethodDeclaration {};

#endif // COMPILERS_02_PARSERS_DECLARATIONS_METHODDECLARATION_H_
