//
// Created by timur on 16.03.2020.
//

#ifndef COMPILERS_02_PARSERS_DECLARATIONS_VARIABLEDECLARATION_H_
#define COMPILERS_02_PARSERS_DECLARATIONS_VARIABLEDECLARATION_H_

class VariableDeclaration {};

#endif // COMPILERS_02_PARSERS_DECLARATIONS_VARIABLEDECLARATION_H_
