//
// Created by timur on 16.03.2020.
//

#ifndef COMPILERS_02_PARSERS_FORMALS_FORMALLIST_H_
#define COMPILERS_02_PARSERS_FORMALS_FORMALLIST_H_

class FormalList {};

#endif // COMPILERS_02_PARSERS_FORMALS_FORMALLIST_H_
