//
// Created by timur on 16.03.2020.
//

#ifndef COMPILERS_02_PARSERS_STATEMENTS_ASSERTSTATEMENT_H_
#define COMPILERS_02_PARSERS_STATEMENTS_ASSERTSTATEMENT_H_

class AssertStatement {};

#endif // COMPILERS_02_PARSERS_STATEMENTS_ASSERTSTATEMENT_H_
