//
// Created by timur on 16.03.2020.
//

#ifndef COMPILERS_02_PARSERS_STATEMENTS_IFSTATEMENT_H_
#define COMPILERS_02_PARSERS_STATEMENTS_IFSTATEMENT_H_

class IfStatement {};

#endif // COMPILERS_02_PARSERS_STATEMENTS_IFSTATEMENT_H_
