//
// Created by timur on 16.03.2020.
//

#ifndef COMPILERS_02_PARSERS_STATEMENTS_LOCALVARIABLEDECLARATIONSTATEMENT_H_
#define COMPILERS_02_PARSERS_STATEMENTS_LOCALVARIABLEDECLARATIONSTATEMENT_H_

class LocalVariableDeclarationStatement {};

#endif // COMPILERS_02_PARSERS_STATEMENTS_LOCALVARIABLEDECLARATIONSTATEMENT_H_
