//
// Created by timur on 16.03.2020.
//

#ifndef COMPILERS_02_PARSERS_STATEMENTS_METHODINVOKATIONSTATEMENT_H_
#define COMPILERS_02_PARSERS_STATEMENTS_METHODINVOKATIONSTATEMENT_H_

class MethodInvokationStatement {};

#endif // COMPILERS_02_PARSERS_STATEMENTS_METHODINVOKATIONSTATEMENT_H_
