//
// Created by timur on 16.03.2020.
//

#ifndef COMPILERS_02_PARSERS_STATEMENTS_RETURNSTATEMENT_H_
#define COMPILERS_02_PARSERS_STATEMENTS_RETURNSTATEMENT_H_

class ReturnStatement {};

#endif // COMPILERS_02_PARSERS_STATEMENTS_RETURNSTATEMENT_H_
