//
// Created by timur on 16.03.2020.
//

#ifndef COMPILERS_02_PARSERS_STATEMENTS_SCOPESTATEMENT_H_
#define COMPILERS_02_PARSERS_STATEMENTS_SCOPESTATEMENT_H_

class ScopeStatement {};

#endif // COMPILERS_02_PARSERS_STATEMENTS_SCOPESTATEMENT_H_
