//
// Created by timur on 16.03.2020.
//

#ifndef COMPILERS_02_PARSERS_STATEMENTS_SOUTSTATEMENT_H_
#define COMPILERS_02_PARSERS_STATEMENTS_SOUTSTATEMENT_H_

class SoutStatement {};

#endif // COMPILERS_02_PARSERS_STATEMENTS_SOUTSTATEMENT_H_
