//
// Created by timur on 16.03.2020.
//

#ifndef COMPILERS_02_PARSERS_STATEMENTS_STATEMENT_H_
#define COMPILERS_02_PARSERS_STATEMENTS_STATEMENT_H_

class Statement {};

#endif // COMPILERS_02_PARSERS_STATEMENTS_STATEMENT_H_
