//
// Created by timur on 16.03.2020.
//

#ifndef COMPILERS_02_PARSERS_STATEMENTS_WHILESTATEMENT_H_
#define COMPILERS_02_PARSERS_STATEMENTS_WHILESTATEMENT_H_

class WhileStatement {};

#endif // COMPILERS_02_PARSERS_STATEMENTS_WHILESTATEMENT_H_
