//
// Created by timur on 16.03.2020.
//

#ifndef COMPILERS_02_PARSERS_TYPES_TYPEIDENTIFIER_H_
#define COMPILERS_02_PARSERS_TYPES_TYPEIDENTIFIER_H_

class TypeIdentifier {};

#endif // COMPILERS_02_PARSERS_TYPES_TYPEIDENTIFIER_H_
