//
// Created by timur on 16.03.2020.
//

#ifndef COMPILERS_02_PARSERS_LVALUES_ARRAYLVALUE_H_
#define COMPILERS_02_PARSERS_LVALUES_ARRAYLVALUE_H_

class ArrayLvalue {};

#endif // COMPILERS_02_PARSERS_LVALUES_ARRAYLVALUE_H_
