//
// Created by timur on 16.03.2020.
//

#ifndef COMPILERS_02_PARSERS_LVALUES_LVALUE_H_
#define COMPILERS_02_PARSERS_LVALUES_LVALUE_H_

class Lvalue {};

#endif // COMPILERS_02_PARSERS_LVALUES_LVALUE_H_
