//
// Created by timur on 16.03.2020.
//

#ifndef COMPILERS_02_PARSERS_LVALUES_SIMPLELVALUE_H_
#define COMPILERS_02_PARSERS_LVALUES_SIMPLELVALUE_H_

class SimpleLvalue {};

#endif // COMPILERS_02_PARSERS_LVALUES_SIMPLELVALUE_H_
