//
// Created by timur on 16.03.2020.
//

#ifndef COMPILERS_02_PARSERS_METHODINVOKATION_H_
#define COMPILERS_02_PARSERS_METHODINVOKATION_H_

class MethodInvokation {};

#endif // COMPILERS_02_PARSERS_METHODINVOKATION_H_
